[2024-10-29T23:29:34.841+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag2.tsk1 manual__2024-10-29T23:29:33.122355+00:00 [queued]>
[2024-10-29T23:29:34.852+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag2.tsk1 manual__2024-10-29T23:29:33.122355+00:00 [queued]>
[2024-10-29T23:29:34.852+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-29T23:29:34.852+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-10-29T23:29:34.852+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-29T23:29:34.868+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-10-29 23:29:33.122355+00:00
[2024-10-29T23:29:34.878+0000] {standard_task_runner.py:55} INFO - Started process 998 to run task
[2024-10-29T23:29:34.883+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdag2', 'tsk1', 'manual__2024-10-29T23:29:33.122355+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag2.py', '--cfg-path', '/tmp/tmpmpy_biat']
[2024-10-29T23:29:34.886+0000] {standard_task_runner.py:83} INFO - Job 102: Subtask tsk1
[2024-10-29T23:29:34.963+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdag2.tsk1 manual__2024-10-29T23:29:33.122355+00:00 [running]> on host 55e2175811f2
[2024-10-29T23:29:35.058+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdag2
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-10-29T23:29:33.122355+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-29T23:29:33.122355+00:00
[2024-10-29T23:29:35.060+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-29T23:29:35.060+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-10-29T23:29:35.079+0000] {subprocess.py:86} INFO - Output:
[2024-10-29T23:29:35.082+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-29T23:29:35.099+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-29T23:29:35.103+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdag2, task_id=tsk1, execution_date=20241029T232933, start_date=20241029T232934, end_date=20241029T232935
[2024-10-29T23:29:35.119+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 102 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 998)
[2024-10-29T23:29:35.134+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-29T23:29:35.171+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
