[2024-10-29T23:08:46.571+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag2.tsk1 manual__2024-10-29T23:08:45.592291+00:00 [queued]>
[2024-10-29T23:08:46.590+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag2.tsk1 manual__2024-10-29T23:08:45.592291+00:00 [queued]>
[2024-10-29T23:08:46.590+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-29T23:08:46.590+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-10-29T23:08:46.590+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-29T23:08:46.616+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-10-29 23:08:45.592291+00:00
[2024-10-29T23:08:46.624+0000] {standard_task_runner.py:55} INFO - Started process 749 to run task
[2024-10-29T23:08:46.628+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdag2', 'tsk1', 'manual__2024-10-29T23:08:45.592291+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag2.py', '--cfg-path', '/tmp/tmp7uda_8k5']
[2024-10-29T23:08:46.629+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask tsk1
[2024-10-29T23:08:46.714+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdag2.tsk1 manual__2024-10-29T23:08:45.592291+00:00 [running]> on host 55e2175811f2
[2024-10-29T23:08:46.794+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdag2
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-10-29T23:08:45.592291+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-29T23:08:45.592291+00:00
[2024-10-29T23:08:46.796+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-29T23:08:46.797+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-10-29T23:08:46.811+0000] {subprocess.py:86} INFO - Output:
[2024-10-29T23:08:46.814+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-29T23:08:46.829+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-29T23:08:46.835+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdag2, task_id=tsk1, execution_date=20241029T230845, start_date=20241029T230846, end_date=20241029T230846
[2024-10-29T23:08:46.854+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 11 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 749)
[2024-10-29T23:08:46.880+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-29T23:08:46.912+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
