[2024-10-29T23:29:36.475+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag3.tsk1 manual__2024-10-29T23:29:35.051208+00:00 [queued]>
[2024-10-29T23:29:36.485+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: triggerdag3.tsk1 manual__2024-10-29T23:29:35.051208+00:00 [queued]>
[2024-10-29T23:29:36.486+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-29T23:29:36.486+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-10-29T23:29:36.486+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-29T23:29:36.501+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-10-29 23:29:35.051208+00:00
[2024-10-29T23:29:36.508+0000] {standard_task_runner.py:55} INFO - Started process 1009 to run task
[2024-10-29T23:29:36.511+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'triggerdag3', 'tsk1', 'manual__2024-10-29T23:29:35.051208+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag3.py', '--cfg-path', '/tmp/tmp0k1ncnak']
[2024-10-29T23:29:36.513+0000] {standard_task_runner.py:83} INFO - Job 105: Subtask tsk1
[2024-10-29T23:29:36.586+0000] {task_command.py:388} INFO - Running <TaskInstance: triggerdag3.tsk1 manual__2024-10-29T23:29:35.051208+00:00 [running]> on host 55e2175811f2
[2024-10-29T23:29:36.676+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=triggerdag3
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-10-29T23:29:35.051208+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-10-29T23:29:35.051208+00:00
[2024-10-29T23:29:36.677+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-10-29T23:29:36.678+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-10-29T23:29:36.692+0000] {subprocess.py:86} INFO - Output:
[2024-10-29T23:29:36.695+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-29T23:29:36.707+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-29T23:29:36.711+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=triggerdag3, task_id=tsk1, execution_date=20241029T232935, start_date=20241029T232936, end_date=20241029T232936
[2024-10-29T23:29:36.721+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 105 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 1009)
[2024-10-29T23:29:36.763+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-29T23:29:36.791+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
